server:
  port: 8053

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/builder
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka